<?php
// $Id$
/**
 * @file
 *    Mysql provisioning module.
 *
 * The goal of this module is to create mysql databases and user accounts, for sites that are about to be created.
 * It uses the provision API to tie into the right places in the site creation work flow.
 */


include_once('provision.mysql.inc');

/**
 * @ingroup provisionui
 * @{
 */

 /**
  * Implementation of hook_help().
  */
 function provision_mysql_help($section) {
   switch ($section) {
     case 'admin/help/provision#requirements':

       $output .= _provision_requirements('mysql_user');
       return $output;
       break;
   }
 }

function _provision_mysql_user_requirements() {
   $username = PROVISION_SCRIPT_USER;
   $command = <<<EOF
     [$username@hm2 ~]$ mysql -uroot -pXXXXXXXXX mysql

     mysql> GRANT ALL PRIVILEGES ON *.* TO 'username_here'@'localhost' IDENTIFIED BY 'mypassword' WITH GRANT OPTION;
     Query OK, 0 rows affected (0.00 sec)

EOF;
   $help['title'] = t('Mysql user account capable of creating new databases.');
   $help['summary'] = t('To be able to create new sites, the provisioning framework will need to be able
     to create new databases and users. It is not recommended using the mysql root password for this, 
     but any account with the correct permissions will do.');
   $help['configuration'] = t('Log in to your mysql server as root, and type in the following command:
     <pre>@command_text</pre>', array('@command_text' => $command));     

  return $help;
}

/**
 * @} end "ingroup provisionui"
 */


function provision_mysql_provision_pre_install($url, &$data) {
  $data['db_type'] = ($data['db_type']) ? $data['db_type'] : PROVISION_DB_TYPE;
  $data['db_host'] = ($data['db_host']) ? $data['db_host'] : PROVISION_DB_HOST;

  # generate a random password for use
  $data['db_passwd'] = user_password(); 
  $data['db_name'] = _provision_mysql_suggest_db_name($url, $data);
  $data['db_user'] = $data['db_name']; 

  return _provision_mysql_new_site_db($data['db_name'], $data['db_user'], $data['db_passwd'], $data['db_host']);
}

function provision_mysql_provision_pre_install_rollback($url, &$data) {
  _provision_mysql_destroy_site_db($data['db_name'], $data['db_user'], $data['db_passwd'], $data['db_host']);
  unset($data['db_host']);
  unset($data['db_type']);
  unset($data['db_passwd']);
  unset($data['db_user']);
  unset($data['db_name']);
}

function provision_mysql_provision_pre_restore($url, &$data) {
  // store a backup of the credentials of the site.
  $data['old_db_name'] = $data['db_name'];
  $data['old_db_passwd'] = $data['db_passwd'];
  $data['old_db_user'] = $data['db_user'];
  $data['old_db_host'] = $data['db_host'];

  # generate a random password for use
  $data['db_passwd'] = user_password(); 
  $data['db_name'] = _provision_mysql_suggest_db_name($url, $data);
  $data['db_user'] = $data['db_name'];

  $success = _provision_mysql_new_site_db($data['db_name'], $data['db_user'], $data['db_passwd'], $data['db_host']);
  if ($success) {
    _provision_mysql_import_dump(PROVISION_SITES_PATH .'/'. $url .'.restore/database.sql', $data['db_name'], $data['db_user'], $data['db_passwd'], $data['db_host']);
  }
  else {
    provision_set_error(PROVISION_DB_ERROR);
    provision_log("error", "could not create new database to be imported into");
  }
}

function provision_mysql_provision_pre_restore_rollback($url, &$data) {
  _provision_mysql_destroy_site_db($data['db_name'], $data['db_user'], $data['db_passwd'], $data['db_host']);

  //Restore the original database credentials of the site.
  foreach ($keys as $key) {
    $data[$key] = $data['old_'. $key];
  }
}

/**
 * Implementation of hook_provision_delete()
 *
 * This will drop the database, revoke the privileges and flush the privileges.
 */
function provision_mysql_provision_delete($url, &$data) {
  return _provision_mysql_destroy_site_db($data['db_name'], $data['db_user'], $data['db_passwd'], $data['db_host']);
}

// Rollback doesn't apply here yet. Unless we trigger a restore of the first dump
// made. Which could go on infinitely if something is really long.
function provision_mysql_provision_post_restore($url, &$data) {
  provision_path('unlink', 'sites/'. $url .'/database.sql', TRUE,
    t("Removed dump file @path after restoring from it"),
    t("Could not remove dump file @path"), PROVISION_PERM_ERROR);
  return _provision_mysql_destroy_site_db($data['old_db_name'], $data['old_db_user'], $data['old_db_passwd'], $data['old_db_host']);
}


function provision_mysql_provision_backup($url, &$data) {
  provision_log("backup", "Generating mysql dump for $url.");
  provision_shell_exec("mysqldump -u%s -p%s %s > sites/%s/database.sql", $data['db_user'], $data['db_passwd'], $data['db_name'], $url); 
  provision_shell_exec("cd sites/%; tar -rf %s database.sql; rm database.sql", $url, $data['backup_file']);
}

/**
 * Implementation of hook_provision_verify
 *
 * Can't be rolled back.
 */
function provision_mysql_provision_verify() {
  provision_set_active_db(_provision_master_db_url());
  if (!_provision_mysql_can_create_database()) {
    provision_set_error(PROVISION_DB_ERROR | PROVISION_FRAMEWORK_ERROR);
    provision_log('error', t('Unable to create new databases.'));
  }
  else {
    provision_log("message", t('Mysql can create new databases.'));
  }
  provision_set_active_db();
}
