<?php
/**
 * @file
 *    Mysql provisioning module.
 *
 * The goal of this module is to create mysql databases and user accounts, for sites that are about to be created.
 * It uses the provision API to tie into the right places in the site creation work flow.
 */


include_once('provision_mysql.inc');

/**
 * @ingroup provisionui
 * @{
 */

 /**
  * Implementation of hook_help().
  */
 function provision_mysql_help($section) {
   switch ($section) {
     case 'admin/help/provision#requirements':
       $username = PROVISION_SCRIPT_USER;
       $output .= "<ol>";
       $command = <<<EOF
     [$username@hm2 ~]$ mysql -uroot -pXXXXXXXXX mysql

     mysql> grant create, drop, grant option  on *.* to 'username_here'@'localhost'
         -> identified by 'mypassword';
     Query OK, 0 rows affected (0.00 sec)

     mysql> flush privileges;
     Query OK, 0 rows affected (0.00 sec)
EOF;
       $output .= '<li>' . t('<p><strong>Mysql user account capable of creating new databases.</strong>
                To be able to create new sites, the provisioning framework will need to be able to create new databases and users. 
                It is not recommended using the mysql root password for this, but any account with the correct permissions will do.</p>
                <p><strong>To configure:</strong> Log in to your mysql server as root, and type in the following command:
                <pre>@command_text</pre></p>', array('@command_text' => $command)) . '</li>';            
       $output .= "</ol>";
       return $output;
       break;
   }
}

/**
 * Implementation of provision_service()
 */
function provision_mysql_provision_service() {
  return array("db_server" => t("Mysql database server"));
}

/**
 * Implementation of provision_configure
 */
function provision_mysql_provision_configure($node = null) {
  if (!is_object($node) && ($nid = variable_get('hosting_own_db_server', 0))) {
    $node = node_load($nid);
  }
  $form['db_type'] = array('#type' => 'hidden', '#value' => ($node->db_type) ? $node->db_type : PROVISION_DB_TYPE);
  
  $form['db_host'] = array(
    '#type' => 'textfield',
    '#title' => t('Mysql server hostname'),
    '#description' => t('The mysql server to connect to.'),
    '#size' => 30,
    '#default_value' => ($node->db_host) ? $node->db_host : PROVISION_DB_HOST,
    '#maxlength' => 64,
  );
  
  $form['db_user'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('Mysql user account'),
    '#description' => t('The user that will be used to create users and databases for new sites.'),
    '#size' => 40,
    '#default_value' => ($node->db_user) ? $node->db_user : PROVISION_DB_USER,
    '#maxlength' => 255,
  );
  if ($node->db_passwd) {
    $passwd_description = t('<strong>You have already set a password for this database server.</strong><br />');
  }
  $form['db_passwd'] = array(
    '#type' => 'password_confirm',
    '#required' => (PROVISION_DB_PASSWD) ? FALSE : TRUE,
    '#title' => t('Mysql user password'),
    '#description' => $passwd_description . t('The user account that will be used to create new mysql users and databases for new sites'),
    '#size' => 30,
  );
  
  return $form;
}
/**
 * @} end "ingroup provisionui"
 */


function provision_mysql_provision_pre_install($url, &$data) {
  $data['site_db_type'] = ($data['site_db_type']) ? $data['site_db_type'] : PROVISION_DB_TYPE;
  $data['site_db_host'] = ($data['site_db_host']) ? $data['site_db_host'] : PROVISION_DB_HOST;

  # generate a random password for use
  $data['site_db_passwd'] = user_password(); 
  $data['site_db_name'] = _provision_mysql_suggest_db_name($url, $data);
  $data['site_db_user'] = $data['site_db_name']; 

  return _provision_mysql_new_site_db($data['site_db_name'], $data['site_db_user'], $data['site_db_passwd'], $data['site_db_host']);

}

function provision_mysql_provision_pre_restore($url, $backup_file, &$data) {
  // store a backup of the credentials of the site.
  $keys = array('site_db_name', 'site_db_passwd', 'site_db_user', 'site_db_host');
  foreach ($keys as $key) {
    $data['old_' . $key] = $data[$key];
  }

  # generate a random password for use
  $data['site_db_passwd'] = user_password(); 
  $data['site_db_name'] = _provision_mysql_suggest_db_name($url, $data);
  $data['site_db_user'] = $data['site_db_name']; 

  $success = _provision_mysql_new_site_db($data['site_db_name'], $data['site_db_user'], $data['site_db_passwd'], $data['site_db_host']);
  if (!$success) {
    // store a backup of the credentials of the site.
    foreach ($keys as $key) {
      $data[$key] = $data['old_' . $key];
    }
    return false; # i really really need to dust up on my rollback code.
  }
  _provision_mysql_import_dump($url, $data);

}

/**
 * Implementation of hook_provision_delete()
 *
 * This will drop the database, revoke the privileges and flush the privileges.
 */
function provision_mysql_provision_delete($url, &$data) {
  return _provision_mysql_destroy_site_db($data['site_db_name'], $data['db_user'], $data['db_passwd'], $data['db_host']);
}

function provision_mysql_provision_post_restore($url, &$data) {
  return _provision_mysql_destroy_site_db($data['old_site_db_name'], $data['old_db_user'], $data['old_db_passwd'], $data['old_db_host']);
}


function provision_mysql_provision_backup($url, &$data) {
  provision_log("backup", "Generating mysql dump for $url.");
  provision_shell_exec("mysqldump -u%s -p%s %s > sites/%s/database.sql", $data['site_db_user'], $data['site_db_passwd'], $data['site_db_name'], $url); 
  provision_shell_exec("cd sites/%; tar -rf %s database.sql; rm database.sql", $url, $data['backup_file']);
}

/**
 * Implementation of hook_provision_verify
 */
function provision_mysql_provision_verify() {
  provision_set_active_db(_provision_master_db_url());
  if (!_provision_mysql_can_create_database()) {
    provision_set_error(PROVISION_DB_ERROR | PROVISION_FRAMEWORK_ERROR);
    provision_log('error', t('Unable to create new databases.'));
  }
  else {
    provision_log("message", t('Mysql can create new databases.'));
  }
  provision_set_active_db();
}





