# Use this Dockerfile for building a new image with your desired UID.
ARG IMAGE_NAME=http
ARG IMAGE_TAG=php7

FROM provision4/$IMAGE_NAME:$IMAGE_TAG

ENV IMAGE_TAG ${IMAGE_TAG:-php7}
ENV IMAGE_NAME ${IMAGE_NAME:-http}

# The UID and GID for the USER_NAME user.
ARG PROVISION_USER_UID=1000
ENV PROVISION_USER_UID ${PROVISION_USER_UID:-1000}

ARG PROVISION_WEB_UID=2000
ENV PROVISION_WEB_UID ${PROVISION_WEB_UID:-2000}

ENV PROVISION_USER_NAME provision

USER root

RUN echo "$RUN_PREFIX Creating set-user-ids script..."
COPY set-user-ids.sh /usr/local/bin/set-user-ids
RUN chmod +x /usr/local/bin/set-user-ids

ENV RUN_PREFIX '𝙋𝙍𝙊𝙑𝙄𝙎𝙄𝙊𝙉 Dockerfile.user ║'

RUN echo "$RUN_PREFIX Running /usr/local/bin/set-user-ids $PROVISION_USER_NAME $PROVISION_USER_UID $PROVISION_WEB_UID"
RUN /usr/local/bin/set-user-ids $PROVISION_USER_NAME $PROVISION_USER_UID $PROVISION_WEB_UID

USER $PROVISION_USER_NAME